# https://medium.com/@ashokrajar/multi-stage-azure-pipeline-for-golang-69261e984621
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - LICENSE.md
      - .travis.yml
      - .github/*
      - .gitignore

pr:
  autoCancel: True # Auto cancel if active pull request updated
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - LICENSE.md
      - .travis.yml
      - .github/*
      - .gitignore

variables:
  GOPATH: '$(Pipeline.Workspace)/gowork'

stages:
  - stage: Test
    jobs:
      - template: templates/azure/jobs/test.yml
